server:
  port: 8087
  servlet:
    context-path: /api


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:mysql://localhost:3306/oneapi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
      #url: jdbc:oracle:thin:@192.168.2.17:41521:xe
      #username: NOCODE
      #password: nocode
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 6000
  profiles:
    active: dev

